### PR TITLE
fix: emit learning events from the LSM hook

### LINKED ISSUE #421: bug: learning phase misses shebang scripts due to hook mismatch between learning and enforcement
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- OS:openSUSE Aeon
- Architecture:x84_65
- Cluster:Kind
```

### Issue Description

When a workload uses shell scripts (e.g., docker-entrypoint.sh), the learning phase fails to capture the script paths in the WorkloadPolicyProposal. After promoting the proposal to a WorkloadPolicy:

- Protect mode: containers fail to start with exec /usr/local/bin/docker-entrypoint.sh: operation not permitted
- Monitor mode: violations are generated for every script execution

This affects any container image that uses shell scripts as entrypoints or during its lifecycle, which is extremely common.

### Reproduction

  1. Install a workload that uses a shell script entrypoint (e.g., NATS)
  2. Wait for the learning phase to generate a WorkloadPolicyProposal
  3. Promote the proposal to a WorkloadPolicy
  4. Bind the workload to the policy
  5. Switch to protect mode
  6. Observe the container failing with operation not permitted on the entrypoint script

### Root Cause

The learning phase and the enforcement phase use two different BPF hooks that see different things for script execution:

- Learning uses the sched_process_exec tracepoint (tp_btf), which fires after the kernel's binfmt resolution completes. For a shebang script, bprm->file points to the final interpreter (e.g., /bin/sh), not the script itself. The script path is never recorded.
- Enforcement uses the security_bprm_creds_for_exec LSM hook (fmod_ret), which fires during search_binary_handler() for each binary in the binfmt chain. For a shebang script, it fires first for the script (docker-entrypoint.sh), then for the interpreter (/bin/sh).

Since the script path is never learned but is checked during enforcement, it is always treated as a violation.

### PR DESCRIPTION
**Pull request by dottorblaster**
**What this PR does / why we need it**:

Fixes the learning/enforcement hook mismatch that caused shebang scripts to be missed during the learning phase, resulting in broken workloads in protect mode and false violations in monitor mode.

**Which issue(s) this PR fixes**

fixes #421 

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits into logical changes
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by flavio** [comment]
However, this is what is seen with this PR, compared to `main`.

## pgsql

Before:

```yaml
spec:
  rulesByContainer:
    pgsql:
      executables:
        allowed:
        - /usr/bin/env
        - /usr/bin/id
        - /usr/bin/mkdir
        - /usr/bin/chmod
        - /usr/bin/find
        - /usr/local/bin/gosu
        - /usr/bin/bash
        - /usr/bin/cat
        - /usr/lib/postgresql/18/bin/postgres
```

Now:

```yaml
spec:
  rulesByContainer:
    pgsql:
      executables:
        allowed:
        - /usr/local/bin/docker-entrypoint.sh
        - /usr/bin/bash
        - /usr/bin/mountpoint
        - /usr/bin/id
        - /usr/bin/mkdir
        - /usr/bin/chmod
        - /usr/bin/find
        - /usr/bin/chown
        - /usr/bin/ls
        - /usr/lib/postgresql/18/bin/initdb
        - /usr/bin/dash
        - /usr/lib/postgresql/18/bin/postgres
        - /usr/local/bin/gosu
        - /usr/bin/getent
        - /usr/bin/locale
        - /usr/lib/postgresql/18/bin/pg_ctl
        - /usr/share/postgresql-common/pg_wrapper
        - /usr/lib/postgresql/18/bin/psql
        - /usr/bin/cat
```

## nginx

Before:

```yaml
spec:
  rulesByContainer:
    nginx:
      executables:
        allowed:
        - /usr/bin/dash
        - /usr/bin/find
        - /usr/bin/basename
        - /usr/bin/touch
        - /usr/bin/grep
        - /usr/bin/dpkg-query
        - /usr/bin/cut
        - /usr/bin/md5sum
        - /usr/bin/sed
        - /usr/bin/mawk
        - /usr/sbin/nginx
        - /usr/bin/sort
```

Now:

```yaml
spec:
  rulesByContainer:
    nginx:
      executables:
        allowed:
        - /docker-entrypoint.sh
        - /usr/bin/find
        - /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
        - /usr/bin/basename
        - /usr/bin/touch
        - /usr/bin/grep
        - /usr/bin/dpkg-query
        - /usr/bin/md5sum
        - /usr/bin/sed
        - /docker-entrypoint.d/20-envsubst-on-templates.sh
        - /usr/bin/mawk
        - /docker-entrypoint.d/30-tune-worker-processes.sh
        - /usr/sbin/nginx
        - /usr/bin/sort
        - /usr/bin/cut
```

## NATS

Before:

```yaml
spec:
  rulesByContainer:
    nats:
      executables:
        allowed:
        - /bin/busybox
        - /usr/local/bin/nats-server
    reloader:
      executables:
        allowed:
        - /bin/busybox
        - /usr/local/bin/nats-server-config-reloader
```

Now:

```yaml
spec:
  rulesByContainer:
    nats:
      executables:
        allowed:
        - /usr/local/bin/docker-entrypoint.sh
        - /usr/local/bin/nats-server
    reloader:
      executables:
        allowed:
        - /entrypoint.sh
        - /usr/local/bin/nats-server-config-reloader
```

File: bpf/main.c [hunk 1]
```diff
@@ -556,8 +508,34 @@ int BPF_PROG(enforce_cgroup_policy, struct linux_binprm *bprm) {
 
 	__u64 *policy_id = bpf_map_lookup_elem(&cg_to_policy_map, &cg_tracker_id);
 	if(!policy_id) {
```
Comment (Andreagit97) [inline bpf/main.c]: we should disable the learning with a load time config
```suggestion
	if(!policy_id && load_time_config.learning_enabled) {
```

File: bpf/main.c [hunk 2]
```diff
@@ -556,8 +508,34 @@ int BPF_PROG(enforce_cgroup_policy, struct linux_binprm *bprm) {
...
+		// for each binary in the binfmt chain (e.g., script AND interpreter), while the
+		// `sched_process_exec` tracepoint only fires once for the final binary. Without
+		// this, shebang scripts (e.g., docker-entrypoint.sh) would never be learned and
+		// would be blocked when the policy is enforced.
+		struct process_evt *levt = get_process_evt();
+		if(!levt) {
+			return 0;
+		}
+		levt->cgid = tg_get_current_cgroup_id();
+		levt->cg_tracker_id = cgrp_get_tracker_id(levt->cgid);
```
Comment (Andreagit97) [inline bpf/main.c]: we already have it
```suggestion
		levt->cg_tracker_id = cg_tracker_id;
```

File: internal/bpf/shebang_test.go [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+		command:         scriptPath,
+		channel:         learningChannel,
+		shouldFindEvent: true,
+	}), "script path must be learned via the LSM hook")
+
+	// The interpreter itself must NOT appear as a learned event;
+	// only the script path should be emitted.
+	resolvedInterpreter, err := filepath.EvalSymlinks(interpreter)
+	require.NoError(t, err, "failed to resolve interpreter path")
+	err = runner.manager.findEventInChannel(learningChannel, runner.cgInfo.id, resolvedInterpreter)
```
Comment (Andreagit97) [inline internal/bpf/shebang_test.go]: Cannot we just use `/usr/bin/true`? We can reuse the helper here https://github.com/rancher-sandbox/runtime-enforcer/pull/431 that just generates a script with `/usr/bin/true`
```suggestion
	err = runner.manager.findEventInChannel(learningChannel, runner.cgInfo.id, "/usr/bin/true")
```
