### PR TITLE
fix: safe shutdown of bpf manager

### LINKED ISSUE #112: Improve ebpf map lifecycle management
The eBPF manager provides update callbacks to other components (eventscraper, resolver) in order to modify ebpf maps. If the eBPF manager is stopped (ctx is closed), it will close the eBPF maps, so it is possible that during the turndown phase, an update function is called on a closed map. It is very likely that this will cause a panic. 
We need to investigate if this is really the case, and if so, what is the best way to prevent this situation. The trivial solution is to use a mutex, but this means that for each map update, we need to take a lock...

Some references to the issue:
* https://github.com/neuvector/runtime-enforcer/blob/eef0cf1638a6e5f737abcbbeb63538cbe8469a14/internal/bpf/cgroup_policy.go#L96
* https://github.com/neuvector/runtime-enforcer/blob/eef0cf1638a6e5f737abcbbeb63538cbe8469a14/internal/bpf/cgtracker.go#L23

### PR DESCRIPTION
**Pull request by holyspectral**
**What this PR does / why we need it**:

1. Add a flag to indicate bpf manager is already shutdown.
2. Make bpf manager's functions return nil error if the bpf manager is already shutdown.

**Which issue(s) this PR fixes**

fixes #112 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

File: internal/bpf/manager_test.go [hunk 1]
```diff
@@ -174,3 +174,49 @@ func TestMultiplePolicies(t *testing.T) {
...
+
+func TestManagerShutdown(t *testing.T) {
+	manager, cleanup, err := waitRunningManager(t)
+	require.NoError(t, err, "Failed to start manager")
+	cleanup()
+
+	// create a cgroup for test.  We just reuse the existing cgroup if it exists.
+	cgroupPath := "/sys/fs/cgroup/system.slice/test-manager-shutdown.scope"
+	_ = os.MkdirAll(cgroupPath, 0755)
+	defer os.RemoveAll(cgroupPath)
```
Comment (Andreagit97) [inline internal/bpf/manager_test.go]: I believe we can remove this code, see below

```suggestion
```

File: internal/bpf/manager.go [hunk 2]
```diff
@@ -195,9 +197,21 @@ func (m *Manager) isKernelPre5_9() bool {
...
 }
 
+func (m *Manager) handleError(err error) error {
+	if err != nil {
+		if m.IsShuttingDown() {
+			return nil
+		}
+		return err
+	}
+	return nil
```
Comment (flavio) [inline internal/bpf/manager.go]: This is a bit more polished, still from one of @Andreagit97's suggestion on the review:

```suggestion
	if err == nil || m.IsShuttingDown() {
		return nil
	}
	return err
```

Comment (Andreagit97) [reply internal/bpf/manager.go]: actually we can even do something like this 
```go
func (m *Manager) handleError(err error) error {
	if m.IsShuttingDown() {
		return nil
	}
	return err
}
```

File: internal/bpf/policy_mode_operation.go [hunk 3]
```diff
@@ -43,13 +43,21 @@ func (m *Manager) deletePolicy(policyID uint64) error {
 
 func (m *Manager) GetPolicyModeUpdateFunc() func(policyID uint64, mode policymode.Mode, op PolicyModeOperation) error {
 	return func(policyID uint64, mode policymode.Mode, op PolicyModeOperation) error {
+		var err error
```
[the remark this answers is not in the document]
Comment (Andreagit97) [reply internal/bpf/policy_mode_operation.go]: nope i was thinking something that we cannot do in golang :laughing: so I would probably say the best approach was what you did

```go
func (m *Manager) GetPolicyModeUpdateFunc() func(policyID uint64, mode policymode.Mode, op PolicyModeOperation) error {
	return func(policyID uint64, mode policymode.Mode, op PolicyModeOperation) error {
		var err error
		switch op {
		case UpdateMode:
			err = m.updatePolicyMode(policyID, mode)
		case DeleteMode:
			err = m.deletePolicy(policyID)
		default:
			panic("unhandled policy mode")
		}
		return m.handleError(err)
	}
}
```
sorry for the noise

[the remark this answers is not in the document]
Comment (holyspectral) [reply internal/bpf/policy_mode_operation.go]: To add, after some thoughts, I keep my current code, which chains the `m.handleErrOnShutdown()` and the real function call in one line, like the below, because I figured it's more readable than having to go back to see how `err` is handled.  

```
return m.handleErrOnShutdown(m.updatePolicyMode(policyID, mode))
```

Of course this kind of topic is always subjective, so feel free to let me know if you have different thoughts.
